version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  jobs:
    pre_create_environment:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
    create_environment:
      - uv venv "${READTHEDOCS_VIRTUALENV_PATH}"
    install:
      - UV_PROJECT_ENVIRONMENT="${READTHEDOCS_VIRTUALENV_PATH}" uv sync --frozen
      # mujoco_warp の autodoc 対応
      - |
        find original/mujoco/mjx/mujoco/mjx/third_party/mujoco_warp -type f \
          -exec sed -i 's/mujoco\.mjx\.third_party\.mujoco_warp/mujoco_warp/g' {} \;
      - python original/mujoco/doc/mjwarp/update_types.py original/mujoco/mjx/mujoco/mjx/third_party/mujoco_warp/_src/types.py
      - UV_PROJECT_ENVIRONMENT="${READTHEDOCS_VIRTUALENV_PATH}" uv pip install original/mujoco/mjx/mujoco/mjx/third_party/mujoco_warp

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: false

submodules:
  include:
    - original/mujoco
  recursive: true
